name: Deploy Docusaurus to GitHub Pages

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

concurrency:
  group: gh-pages-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/krypton'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        working-directory: ./website
        run: npm ci

      - name: Build Docusaurus
        working-directory: ./website
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
